stages:
  - build
  - test

build:
  stage : build
  script: tasks/build.ps1
  tags:
  - windows
  - powershell

test:
  stage : test
  script: invoke-Pester -path tests/GPOToolsUtility.tests.ps1
  tags:
  - windows
  - powershell
