stages:
  - build
  - test

build:
  stage : build
  script: tasks/build.ps1
  tags:
  - PowerShell

test:
  stage : test
  script:
  - $Result = invoke-Pester -path tests/GPOToolsUtility.tests.ps1 -PassThru
  - if ($Result.FailedCount -ne 0){
  - Throw ("{0} Test Failed" -f $Result.FailedCount)
  }
  tags:
  - PowerShell
